name: build

on:
  push:
    branches:
      - main

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - name: Install packages
        run: sudo apt install latexmk texlive texlive-latex-extra texlive-publishers
      - name: Typeset
        run: latexmk -pdf
      - uses: actions/upload-pages-artifact@v3
        with:
          path: m4opt.pdf

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: latex
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
