name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install latexmk texlive texlive-latex-extra texlive-publishers
      - name: Typeset
        run: latexmk -pdf
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          path: m4opt.pdf
